// THIS IS AUTOGENERATED BY gen_flags.py
// start --gen_flags.py--
#include <stddef.h>

// rena flags
// Enable a trailing/leading dot when reading a floating point number
typedef struct _rena_dot { int _; } RENA_DOT;
// Enable seperator '_' characters in the middle of the number
typedef struct _rena_sep { int _; } RENA_SEP;
// Read or write ONLY binary (base 2, no prefix) numbers
typedef struct _rena_bin { int _; } RENA_BIN;
// Read or write ONLY octal (base 8, no prefix) numbers
typedef struct _rena_oct { int _; } RENA_OCT;
// Read or write ONLY decimal (base 10, no prefix) numbers
typedef struct _rena_dec { int _; } RENA_DEC;
// Read or write ONLY hexadecimal (base 16, no prefix) numbers
typedef struct _rena_hex { int _; } RENA_HEX;


#define _RENA_RD0(str, out) (_Generic(*(out) \
	, uint64_t : _rena_rd_u64 \
	, int64_t : _rena_rd_i64 \
	, double : _rena_rd_f64 \
	, default : _rena_rd_err_type \
))(str, out) 
#define _RENA_RD1(str, out, flag0) (_Generic((flag0){0}, \
	RENA_DOT : _Generic(*(out) \
		, uint64_t : _rena_rd_err_type_flags \
		, int64_t : _rena_rd_err_type_flags \
		, double : _rena_rd_dot_f64 \
		, default : _rena_rd_err_type \
	), \
	RENA_SEP : _Generic(*(out) \
		, uint64_t : _rena_rd_sep_u64 \
		, int64_t : _rena_rd_sep_i64 \
		, double : _rena_rd_sep_f64 \
		, default : _rena_rd_err_type \
	), \
	RENA_BIN : _Generic(*(out) \
		, uint64_t : _rena_rd_bin_u64 \
		, int64_t : _rena_rd_bin_i64 \
		, double : _rena_rd_err_type_flags \
		, default : _rena_rd_err_type \
	), \
	RENA_OCT : _Generic(*(out) \
		, uint64_t : _rena_rd_oct_u64 \
		, int64_t : _rena_rd_oct_i64 \
		, double : _rena_rd_err_type_flags \
		, default : _rena_rd_err_type \
	), \
	RENA_DEC : _Generic(*(out) \
		, uint64_t : _rena_rd_dec_u64 \
		, int64_t : _rena_rd_dec_i64 \
		, double : _rena_rd_dec_f64 \
		, default : _rena_rd_err_type \
	), \
	RENA_HEX : _Generic(*(out) \
		, uint64_t : _rena_rd_hex_u64 \
		, int64_t : _rena_rd_hex_i64 \
		, double : _rena_rd_hex_f64 \
		, default : _rena_rd_err_type \
	), \
	default : _rena_rd_err_flag \
) \
)(str, out) 
#define _RENA_RD2(str, out, flag0, flag1) (_Generic((flag0){0}, \
	RENA_DOT : _Generic((flag1){0}, \
		RENA_DOT : _rena_rd_err_flag_type, \
		RENA_SEP : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_dot_sep_f64 \
			, default : _rena_rd_err_type \
		), \
		RENA_BIN : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_err_type_flags \
			, default : _rena_rd_err_type \
		), \
		RENA_OCT : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_err_type_flags \
			, default : _rena_rd_err_type \
		), \
		RENA_DEC : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_dot_dec_f64 \
			, default : _rena_rd_err_type \
		), \
		RENA_HEX : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_dot_hex_f64 \
			, default : _rena_rd_err_type \
		), \
		default : _rena_rd_err_flag \
	), \
	RENA_SEP : _Generic((flag1){0}, \
		RENA_DOT : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_dot_sep_f64 \
			, default : _rena_rd_err_type \
		), \
		RENA_SEP : _rena_rd_err_flag_type, \
		RENA_BIN : _Generic(*(out) \
			, uint64_t : _rena_rd_sep_bin_u64 \
			, int64_t : _rena_rd_sep_bin_i64 \
			, double : _rena_rd_err_type_flags \
			, default : _rena_rd_err_type \
		), \
		RENA_OCT : _Generic(*(out) \
			, uint64_t : _rena_rd_sep_oct_u64 \
			, int64_t : _rena_rd_sep_oct_i64 \
			, double : _rena_rd_err_type_flags \
			, default : _rena_rd_err_type \
		), \
		RENA_DEC : _Generic(*(out) \
			, uint64_t : _rena_rd_sep_dec_u64 \
			, int64_t : _rena_rd_sep_dec_i64 \
			, double : _rena_rd_sep_dec_f64 \
			, default : _rena_rd_err_type \
		), \
		RENA_HEX : _Generic(*(out) \
			, uint64_t : _rena_rd_sep_hex_u64 \
			, int64_t : _rena_rd_sep_hex_i64 \
			, double : _rena_rd_sep_hex_f64 \
			, default : _rena_rd_err_type \
		), \
		default : _rena_rd_err_flag \
	), \
	RENA_BIN : _Generic((flag1){0}, \
		RENA_DOT : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_err_type_flags \
			, default : _rena_rd_err_type \
		), \
		RENA_SEP : _Generic(*(out) \
			, uint64_t : _rena_rd_sep_bin_u64 \
			, int64_t : _rena_rd_sep_bin_i64 \
			, double : _rena_rd_err_type_flags \
			, default : _rena_rd_err_type \
		), \
		RENA_BIN : _rena_rd_err_flag_type, \
		RENA_OCT : _rena_rd_err_flag_type, \
		RENA_DEC : _rena_rd_err_flag_type, \
		RENA_HEX : _rena_rd_err_flag_type, \
		default : _rena_rd_err_flag \
	), \
	RENA_OCT : _Generic((flag1){0}, \
		RENA_DOT : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_err_type_flags \
			, default : _rena_rd_err_type \
		), \
		RENA_SEP : _Generic(*(out) \
			, uint64_t : _rena_rd_sep_oct_u64 \
			, int64_t : _rena_rd_sep_oct_i64 \
			, double : _rena_rd_err_type_flags \
			, default : _rena_rd_err_type \
		), \
		RENA_BIN : _rena_rd_err_flag_type, \
		RENA_OCT : _rena_rd_err_flag_type, \
		RENA_DEC : _rena_rd_err_flag_type, \
		RENA_HEX : _rena_rd_err_flag_type, \
		default : _rena_rd_err_flag \
	), \
	RENA_DEC : _Generic((flag1){0}, \
		RENA_DOT : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_dot_dec_f64 \
			, default : _rena_rd_err_type \
		), \
		RENA_SEP : _Generic(*(out) \
			, uint64_t : _rena_rd_sep_dec_u64 \
			, int64_t : _rena_rd_sep_dec_i64 \
			, double : _rena_rd_sep_dec_f64 \
			, default : _rena_rd_err_type \
		), \
		RENA_BIN : _rena_rd_err_flag_type, \
		RENA_OCT : _rena_rd_err_flag_type, \
		RENA_DEC : _rena_rd_err_flag_type, \
		RENA_HEX : _rena_rd_err_flag_type, \
		default : _rena_rd_err_flag \
	), \
	RENA_HEX : _Generic((flag1){0}, \
		RENA_DOT : _Generic(*(out) \
			, uint64_t : _rena_rd_err_type_flags \
			, int64_t : _rena_rd_err_type_flags \
			, double : _rena_rd_dot_hex_f64 \
			, default : _rena_rd_err_type \
		), \
		RENA_SEP : _Generic(*(out) \
			, uint64_t : _rena_rd_sep_hex_u64 \
			, int64_t : _rena_rd_sep_hex_i64 \
			, double : _rena_rd_sep_hex_f64 \
			, default : _rena_rd_err_type \
		), \
		RENA_BIN : _rena_rd_err_flag_type, \
		RENA_OCT : _rena_rd_err_flag_type, \
		RENA_DEC : _rena_rd_err_flag_type, \
		RENA_HEX : _rena_rd_err_flag_type, \
		default : _rena_rd_err_flag \
	), \
	default : _rena_rd_err_flag \
) \
)(str, out) 
#define _RENA_RD3(str, out, flag0, flag1, flag2) (_Generic((flag0){0}, \
	RENA_DOT : _Generic((flag1){0}, \
		RENA_DOT : _rena_rd_err_flag_type, \
		RENA_SEP : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_OCT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_DEC : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_dec_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_HEX : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_hex_f64 \
				, default : _rena_rd_err_type \
			), \
			default : _rena_rd_err_flag \
		), \
		RENA_BIN : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_OCT : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_DEC : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_dec_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_HEX : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_hex_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		default : _rena_rd_err_flag \
	), \
	RENA_SEP : _Generic((flag1){0}, \
		RENA_DOT : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_OCT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_DEC : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_dec_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_HEX : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_hex_f64 \
				, default : _rena_rd_err_type \
			), \
			default : _rena_rd_err_flag \
		), \
		RENA_SEP : _rena_rd_err_flag_type, \
		RENA_BIN : _Generic((flag2){0}, \
			RENA_DOT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_OCT : _Generic((flag2){0}, \
			RENA_DOT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_DEC : _Generic((flag2){0}, \
			RENA_DOT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_dec_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_HEX : _Generic((flag2){0}, \
			RENA_DOT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_hex_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		default : _rena_rd_err_flag \
	), \
	RENA_BIN : _Generic((flag1){0}, \
		RENA_DOT : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_SEP : _Generic((flag2){0}, \
			RENA_DOT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_BIN : _rena_rd_err_flag_type, \
		RENA_OCT : _rena_rd_err_flag_type, \
		RENA_DEC : _rena_rd_err_flag_type, \
		RENA_HEX : _rena_rd_err_flag_type, \
		default : _rena_rd_err_flag \
	), \
	RENA_OCT : _Generic((flag1){0}, \
		RENA_DOT : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_SEP : _Generic((flag2){0}, \
			RENA_DOT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_err_type_flags \
				, default : _rena_rd_err_type \
			), \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_BIN : _rena_rd_err_flag_type, \
		RENA_OCT : _rena_rd_err_flag_type, \
		RENA_DEC : _rena_rd_err_flag_type, \
		RENA_HEX : _rena_rd_err_flag_type, \
		default : _rena_rd_err_flag \
	), \
	RENA_DEC : _Generic((flag1){0}, \
		RENA_DOT : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_dec_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_SEP : _Generic((flag2){0}, \
			RENA_DOT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_dec_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_BIN : _rena_rd_err_flag_type, \
		RENA_OCT : _rena_rd_err_flag_type, \
		RENA_DEC : _rena_rd_err_flag_type, \
		RENA_HEX : _rena_rd_err_flag_type, \
		default : _rena_rd_err_flag \
	), \
	RENA_HEX : _Generic((flag1){0}, \
		RENA_DOT : _Generic((flag2){0}, \
			RENA_DOT : _rena_rd_err_flag_type, \
			RENA_SEP : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_hex_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_SEP : _Generic((flag2){0}, \
			RENA_DOT : _Generic(*(out) \
				, uint64_t : _rena_rd_err_type_flags \
				, int64_t : _rena_rd_err_type_flags \
				, double : _rena_rd_dot_sep_hex_f64 \
				, default : _rena_rd_err_type \
			), \
			RENA_SEP : _rena_rd_err_flag_type, \
			RENA_BIN : _rena_rd_err_flag_type, \
			RENA_OCT : _rena_rd_err_flag_type, \
			RENA_DEC : _rena_rd_err_flag_type, \
			RENA_HEX : _rena_rd_err_flag_type, \
			default : _rena_rd_err_flag \
		), \
		RENA_BIN : _rena_rd_err_flag_type, \
		RENA_OCT : _rena_rd_err_flag_type, \
		RENA_DEC : _rena_rd_err_flag_type, \
		RENA_HEX : _rena_rd_err_flag_type, \
		default : _rena_rd_err_flag \
	), \
	default : _rena_rd_err_flag \
) \
)(str, out) 


#define _RENA_NPARAM(_IGNORE, _0, _1, _2, MACRO_NAME, ...) MACRO_NAME
#define rena_rd(str, out, ...) _RENA_NPARAM(_IGNORE, ##__VA_ARGS__ \
                                            , _RENA_RD3 \
                                            , _RENA_RD2 \
                                            , _RENA_RD1 \
                                            , _RENA_RD0 \
                                            , ...)(str, out, ##__VA_ARGS__)


#define _RENA_ERROR_TYPE __attribute__((error( \
"\n=======================================\n" \
"RENA_ERR - UNSUPPORTED TYPE" \
"\n=======================================")))
#define _RENA_ERROR_FLAG __attribute__((error( \
"\n=======================================\n" \
"RENA_ERR - NOT A RENA FLAG" \
"\n=======================================")))
#define _RENA_ERROR_TYPEFLAG __attribute__((error( \
"\n=======================================\n" \
"RENA_ERR - INVALID TYPE OR FLAG COMBO" \
"\n=======================================")))

static _RENA_ERROR_TYPE const char *_rena_rd_err_type(const char *str, void *out) {
	return NULL;
}
static _RENA_ERROR_FLAG const char *_rena_rd_err_flag(const char *str, void *out) {
	return NULL;
}
static _RENA_ERROR_TYPEFLAG const char *_rena_rd_err_type_flags(const char *str, void *out) {
	return NULL;
}
static _RENA_ERROR_TYPE const char *_rena_rdsafe_err_type(const char *str, size_t len, void *out) {
	return NULL;
}

static _RENA_ERROR_FLAG const char *_rena_rdsafe_err_flag(const char *str, size_t len, void *out) {
	return NULL;
}

static _RENA_ERROR_TYPEFLAG const char *_rena_rdsafe_err_type_flags(const char *str, size_t len, void *out) {
	return NULL;
}
static _RENA_ERROR_TYPE const char *_rena_wr_err_type(char *buf, size_t len, int _num) {
	return NULL;
}
static _RENA_ERROR_FLAG const char *_rena_wr_err_flag(char *buf, size_t len, int _num) {
	return NULL;
}
static _RENA_ERROR_TYPEFLAG const char *_rena_wr_err_type_flags(char *buf, size_t len, int _num) {
	return NULL;
}

// end --gen_flags.py--

